# %%
"""
This script is used to populate the quam generated by running generate_quam.py with initial values based on previous
calibrations or chip manufacturer specs and must be run prior to conducting the first experiment.
It is split according to the component to update (resonator, qubit xy drive, flux line) and allows the user to specify
the different frequencies and power involved. Other parameters are directly related to the control hardware such as
full_scale_power_dbm, band, upsampling_mode...
The last section is dedicated to adding pulses for the single qubit gates and setting the initial values for the
readout and saturation pulses.
"""

########################################################################################################################
# %%                                             Import section
########################################################################################################################
import json
from qualang_tools.units import unit
from quam_config import Quam
from quam_builder.builder.superconducting.pulses import (
    add_DragCosine_pulses,
    add_default_transmon_pair_pulses,
)
from quam.components import pulses
import numpy as np
from pprint import pprint

########################################################################################################################
# %%                                 QUAM loading and auxiliary functions
########################################################################################################################
# Loads the QUAM
machine = Quam.load()
# Class containing tools to help handling units and conversions.
u = unit(coerce_to_integer=True)


def get_band(freq):
    """Determine the MW fem DAC band corresponding to a given frequency.

    Args:
        freq (float): The frequency in Hz.

    Returns:
        int: The Nyquist band number.
            - 1 if 50 MHz <= freq < 5.5 GHz
            - 2 if 4.5 GHz <= freq < 7.5 GHz
            - 3 if 6.5 GHz <= freq <= 10.5 GHz

    Raises:
        ValueError: If the frequency is outside the MW fem bandwidth [50 MHz, 10.5 GHz].
    """
    if 50e6 <= freq < 5.5e9:
        return 1
    elif 4.5e9 <= freq < 7.5e9:
        return 2
    elif 6.5e9 <= freq <= 10.5e9:
        return 3
    else:
        raise ValueError(f"The specified frequency {freq} Hz is outside of the MW fem bandwidth [50 MHz, 10.5 GHz]")


def closest_number(lst, target):
    return min(lst, key=lambda x: abs(x - target))


def get_full_scale_power_dBm_and_amplitude(desired_power: float, max_amplitude: float = 0.5) -> tuple[int, float]:
    """Get the full_scale_power_dbm and waveform amplitude for the MW FEM to output the specified desired power.

    The keyword `full_scale_power_dbm` is the maximum power of normalized pulse waveforms in [-1,1].
    To convert to voltage:
        power_mw = 10**(full_scale_power_dbm / 10)
        max_voltage_amp = np.sqrt(2 * power_mw * 50 / 1000)
        amp_in_volts = waveform * max_voltage_amp
        ^ equivalent to OPX+ amp
    Its range is -11dBm to +16dBm with 3dBm steps.

    Args:
        desired_power (float): Desired output power in dBm.
        max_amplitude (float, optional): Maximum allowed waveform amplitude in V. Default is 0.5V.

    Returns:
        tuple[float, float]: The full_scale_power_dBm and waveform amplitude realizing the desired power.
    """
    allowed_powers = [-11, -8, -5, -2, 1, 4, 7, 10, 13, 16]
    resulting_power = desired_power - 20 * np.log10(max_amplitude)
    if resulting_power < 0:
        full_scale_power_dBm = closest_number(allowed_powers, max(resulting_power + 3, -11))
    else:
        full_scale_power_dBm = closest_number(allowed_powers, min(resulting_power + 3, 16))
    amplitude = 10 ** ((desired_power - full_scale_power_dBm) / 20)
    if -11 <= full_scale_power_dBm <= 16 and -1 <= amplitude <= 1:
        return full_scale_power_dBm, amplitude
    else:
        raise ValueError(
            f"The desired power is outside the specifications ([-11; +16]dBm, [-1; +1]), got ({full_scale_power_dBm}; {amplitude})"
        )

# # LOAD YAML file
# import yaml

# with open(r"C:\Users\wook9\codes\QM_New\CS_installations-HI_16Jun2025\workspaces\setup_info\250613_YD27Q_OPX1K.yaml") as stream:
#     try:
#         config_yaml = yaml.safe_load(stream)
#     except yaml.YAMLError as exc:
#         print(exc)



########################################################################################################################
# %%                                    Resonator parameters
########################################################################################################################
# Update frequencies - be aware of coupled ports for bands
# The keyword "band" refers to the following frequency bands:
#   1: (50 MHz - 5.5 GHz)
#   2: (4.5 GHz - 7.5 GHz)
#   3: (6.5 GHz - 10.5 GHz)
# Note that the "coupled" ports O1 & I1, O2 & O3, O4 & O5, O6 & O7, and O8 & I2 must be in the same band.

# Resonator frequencies
# for k,v in config_yaml["individual"].items():
#     q_idx = int(k.split("q")[-1])
#     print(f"{v['ro_freq'] / 1e9:4.3f}, # {k}")
rr_freq = np.array([
    7.003, # q1
    7.037, # q2
    7.075, # q3
    7.114, # q4
    7.154, # q5
    7.188, # q6
    7.231, # q7
    7.271, # q8
    7.311, # q9
    6.997, # q10
    7.035, # q11
    7.076, # q12
    7.114, # q13
    7.151, # q14
    7.193, # q15
    7.229, # q16
    7.272, # q17
    7.307, # q18
    6.997, # q19
    7.035, # q20
    7.071, # q21
    7.110, # q22
    7.149, # q23
    7.189, # q24
    7.228, # q25
    7.269, # q26
    7.307, # q27
]) * u.GHz

# for k,v in config_yaml["individual"].items():
#     q_idx = int(k.split("q")[-1])
#     print(f"{float(v['ro_lo_freq']) / 1e9:4.3f}, # {k}")
rr_LO = np.array([
    6.950, # q1
    6.950, # q2
    6.950, # q3
    6.950, # q4
    6.950, # q5
    6.950, # q6
    6.950, # q7
    6.950, # q8
    6.950, # q9
    6.950, # q10
    6.950, # q11
    6.950, # q12
    6.950, # q13
    6.950, # q14
    6.950, # q15
    6.950, # q16
    6.950, # q17
    6.950, # q18
    6.950, # q19
    6.950, # q20
    6.950, # q21
    6.950, # q22
    6.950, # q23
    6.950, # q24
    6.950, # q25
    6.950, # q26
    6.950, # q27
]) * u.GHz

rr_if = rr_freq - rr_LO  # The intermediate frequency is inferred from the LO and readout frequencies

assert np.all(np.abs(rr_if) < 400 * u.MHz), (
    "The resonator intermediate frequency must be within [-400; 400] MHz. \n"
    f"Readout frequencies: {rr_freq} \n"
    f"Readout LO frequency: {rr_LO} \n"
    f"Readout IF frequencies: {rr_if} \n"
)

# Desired output power in dBm - Must be within [-80, 16] dBm
readout_power = -11
# Get the full_scale_power_dBm and waveform amplitude corresponding to the desired powers
rr_full_scale, rr_amplitude = get_full_scale_power_dBm_and_amplitude(
    readout_power, max_amplitude=0.25 / len(machine.qubits)
)

# Update qubit rr freq and power
for k, qubit in enumerate(machine.qubits.values()):
    qubit.resonator.f_01 = rr_freq.tolist()[k]  # Resonator frequency optimized for discriminating 0 (|g>) and 1 (|e>)
    qubit.resonator.RF_frequency = qubit.resonator.f_01  # Readout frequency
    qubit.resonator.opx_output.full_scale_power_dbm = rr_full_scale  # Max readout power in dBm
    qubit.resonator.opx_output.upconverter_frequency = rr_LO[k]  # Readout up-converter frequency
    qubit.resonator.opx_input.band = get_band(rr_LO[k])  # Readout band for the up-conversion
    qubit.resonator.opx_output.band = get_band(rr_LO[k])  # Readout band for the down-conversion


########################################################################################################################
# %%                                    Qubit parameters
########################################################################################################################
# The keyword "band" refers to the following frequency bands:
#   1: (50 MHz - 5.5 GHz)
#   2: (4.5 GHz - 7.5 GHz)
#   3: (6.5 GHz - 10.5 GHz)
# Note that the "coupled" ports O1 & I1, O2 & O3, O4 & O5, O6 & O7, and O8 & I2 must be in the same band.

# Qubit drive frequencies
# for k,v in config_yaml["individual"].items():
#     q_idx = int(k.split("q")[-1])
#     print(f"{float(v['gate_freq']) / 1e9:4.3f}, # {k}")
xy_freq = np.array([
    5.250, # q1
    5.123, # q2
    5.124, # q3
    5.080, # q4
    5.101, # q5
    5.070, # q6
    5.247, # q7
    5.188, # q8
    5.191, # q9
    5.042, # q10
    4.916, # q11
    5.222, # q12
    4.980, # q13
    5.200, # q14
    5.120, # q15
    5.249, # q16
    5.142, # q17
    5.042, # q18
    5.173, # q19
    5.092, # q20
    5.032, # q21
    5.034, # q22
    5.003, # q23
    5.146, # q24
    5.205, # q25
    5.065, # q26
    5.074, # q27
]) * u.GHz

# for k,v in config_yaml["individual"].items():
#     q_idx = int(k.split("q")[-1])
#     print(f"{float(v['drv_lo_freq']) / 1e9:4.3f}, # {k}")
xy_LO = np.array([
    5.050, # q1
    5.050, # q2
    5.000, # q3
    5.000, # q4
    5.000, # q5
    5.000, # q6
    5.050, # q7
    5.050, # q8
    4.950, # q9
    5.100, # q10
    5.100, # q11
    5.050, # q12
    5.050, # q13
    5.050, # q14
    5.050, # q15
    5.050, # q16
    5.050, # q17
    4.950, # q18
    5.000, # q19
    5.000, # q20
    4.950, # q21
    4.950, # q22
    4.950, # q23
    4.950, # q24
    5.050, # q25
    5.000, # q26
    5.000, # q27
]) * u.GHz

xy_if = xy_freq - xy_LO  # The intermediate frequency is inferred from the LO and qubit frequencies
assert np.all(np.abs(xy_if) < 400 * u.MHz), (
    "The xy intermediate frequency must be within [-400; 400] MHz. \n"
    f"Qubit drive frequencies: {xy_freq} \n"
    f"Qubit drive LO frequencies: {xy_LO} \n"
    f"Qubit drive IF frequencies: {xy_if} \n"
)
# Transmon anharmonicity
# for k,v in config_yaml["individual"].items():
#     q_idx = int(k.split("q")[-1])
#     print(f"{-float(v['anharmonicity']) / 1e6:4.1f}, # {k}")
anharmonicity = np.array([
    260.0, # q1
    260.0, # q2
    280.0, # q3
    280.0, # q4
    280.0, # q5
    260.0, # q6
    260.0, # q7
    260.0, # q8
    260.0, # q9
    260.0, # q10
    260.0, # q11
    260.0, # q12
    260.0, # q13
    260.0, # q14
    260.0, # q15
    260.0, # q16
    260.0, # q17
    260.0, # q18
    260.0, # q19
    260.0, # q20
    260.0, # q21
    260.0, # q22
    260.0, # q23
    260.0, # q24
    260.0, # q25
    260.0, # q26
    260.0, # q27
]) * u.MHz

# Desired output power in dBm
drive_power = -11
# Get the full_scale_power_dBm and waveform amplitude corresponding to the desired powers
xy_full_scale, xy_amplitude = get_full_scale_power_dBm_and_amplitude(drive_power)

# Update qubit xy freq and power
for k, qubit in enumerate(machine.qubits.values()):
    qubit.f_01 = xy_freq.tolist()[k]  # Qubit 0 to 1 (|g> -> |e>) transition frequency
    qubit.xy.RF_frequency = qubit.f_01  # Qubit drive frequency
    qubit.xy.opx_output.full_scale_power_dbm = xy_full_scale  # Max drive power in dBm
    qubit.xy.opx_output.upconverter_frequency = xy_LO.tolist()[k]  # Qubit drive up-converter frequency
    qubit.xy.opx_output.band = get_band(xy_LO.tolist()[k])  # Qubit drive band for the up-conversion



rr_slots = [
    3, 3, 3, 3, 3, 3, 3, 3, 3,
    4, 4, 4, 4, 4, 4, 4, 4, 4,
    5, 5, 5, 5, 5, 5, 5, 5, 5,
]
xy_slots = [
    3, 3, 3, 3, 3, 3, 3, 2, 2,
    4, 4, 4, 4, 2, 4, 4, 4, 2,
    5, 5, 5, 5, 5, 5, 5, 2, 2,
]
for k, qubit in enumerate(machine.qubits.values()):
    qubit.resonator.core = f"{qubit.name}_slot{rr_slots[k]}"
    qubit.xy.core = f"{qubit.name}_slot{xy_slots[k]}"

########################################################################################################################
# %%                                        Plot parameters
########################################################################################################################

# Grid layout (2 columns: column 0 and column 1, from top to bottom)
# Each entry is in the format "column-row" (i.e., "col-row")
#
#   0,3 | 1,3
#   0,2 | 1,2
#   0,1 | 1,1
#   0,0 | 1,0
#
# Represented in row,major order from top row (3) to bottom row (0)

grid_locations = [
    "0,8", "0,7", "0,6", "0,5", "0,4", "0,3", "0,2", "0,1", "0,0",
    "1,8", "1,7", "1,6", "1,5", "1,4", "1,3", "1,2", "1,1", "1,0",
    "2,8", "2,7", "2,6", "2,5", "2,4", "2,3", "2,2", "2,1", "2,0",
]
for gd, qubit in zip(grid_locations, machine.qubits.values()):
    qubit.grid_location = gd  # Qubit grid location for plotting as "column,row"



########################################################################################################################
# %%                                        Pulse parameters
########################################################################################################################
# How to add new pulses
# from quam.components.pulses import (
#     SquarePulse,
#     DragGaussianPulse,
#     DragCosinePulse,
#     FlatTopGaussianPulse,
#     WaveformPulse,
#     SquareReadoutPulse,
# )
# e.g., machine.qubits[q].xy.operations["new_pulse"] = FlatTopGaussianPulse(...)

## Update pulses
for k, q in enumerate(machine.qubits):
    # readout
    machine.qubits[q].resonator.operations["readout"].length = 1.0 * u.us
    machine.qubits[q].resonator.operations["readout"].amplitude = rr_amplitude
    # Qubit saturation
    machine.qubits[q].xy.operations["saturation"].length = 30 * u.us
    machine.qubits[q].xy.operations["saturation"].amplitude = 0.5 * xy_amplitude
    # Single qubit gates - DragCosine
    add_DragCosine_pulses(
        machine.qubits[q],
        amplitude=xy_amplitude,
        length=40,
        anharmonicity=anharmonicity.tolist()[k],
        alpha=0.0,
        detuning=0,
    )
    # # resonator const
    machine.qubits[q].resonator.operations["const"] = pulses.SquarePulse(
        length=1 * u.us,
        amplitude=0.5,
        axis_angle=0.0,
    )
    # Qubit const
    machine.qubits[q].xy.operations["const"] = pulses.SquarePulse(
        length=1 * u.us,
        amplitude=0.5,
        axis_angle=0.0,
    )

# for k, qp in enumerate(machine.qubit_pairs):
#     add_default_transmon_pair_pulses(qp)
#     qb_pair = machine.qubit_pairs[qp]
#     qbt = qb_pair.qubit_target
#     qb_pair.cross_resonance.target_qubit_LO_frequency = f"#/qubits/{qbt.name}/xy/LO_frequency"
#     qb_pair.cross_resonance.target_qubit_IF_frequency = f"#/qubits/{qbt.name}/xy/intermediate_frequency"
#     qb_pair.cross_resonance.intermediate_frequency = f"#./inferred_intermediate_frequency"

#     # square
#     qb_pair.cross_resonance.operations["square"] = pulses.SquarePulse(
#         length=16,
#         amplitude=1.0,
#         axis_angle=0.0,
#     )
#     qb_pair.qubit_target.xy.operations["cr_square"] = pulses.SquarePulse(
#         length=16,
#         amplitude=1.0,
#         axis_angle=0.0,
#     )
#     # cosine
#     qb_pair.cross_resonance.operations["cosine"] = pulses.DragCosinePulse(
#         length=16,
#         amplitude=1.0,
#         axis_angle=0.0,
#         anharmonicity=260 * u.MHz,
#         alpha=0.0,
#         detuning=0,
#     )
#     qb_pair.qubit_target.xy.operations["cr_cosine"]= pulses.DragCosinePulse(
#         length=16,
#         amplitude=1.0,
#         axis_angle=0.0,
#         anharmonicity=260 * u.MHz,
#         alpha=0.0,
#         detuning=0,
#     )
#     # gauss
#     qb_pair.cross_resonance.operations["gauss"] = pulses.DragGaussianPulse(
#         length=16,
#         sigma=16/5,
#         amplitude=1.0,
#         axis_angle=0.0,
#         anharmonicity=260 * u.MHz,
#         alpha=0.0,
#         detuning=0,
#     )
#     qb_pair.qubit_target.xy.operations["cr_gauss"]= pulses.DragGaussianPulse(
#         length=16,
#         sigma=16/5,
#         amplitude=1.0,
#         axis_angle=0.0,
#         anharmonicity=260 * u.MHz,
#         alpha=0.0,
#         detuning=0,
#     )

#     # flattop
#     rise_fall_len = 8
#     flattop_lens = np.arange(0, 80, 20).tolist() # must be python list (not numpy array)
#     for flattop_len in flattop_lens:
#         qb_pair.cross_resonance.operations[f"flattop_{flattop_len:04d}"] = pulses.FlatTopGaussianPulse(
#             amplitude=1.0,
#             length=rise_fall_len + flattop_len + rise_fall_len,
#             flat_length=flattop_len,
#             axis_angle=0.0, 
#         )
#         qb_pair.qubit_target.xy.operations[f"cr_flattop_{flattop_len:04d}"] = pulses.FlatTopGaussianPulse(
#             amplitude=1.0,
#             length=rise_fall_len + flattop_len + rise_fall_len,
#             flat_length=flattop_len,
#             axis_angle=0.0, 
#         )




########################################################################################################################
# %%                                         Save the updated QUAM
########################################################################################################################
# save into state.json
machine.save()
# Visualize the QUA config and save it
pprint(machine.generate_config())
with open("qua_config.json", "w+") as f:
    json.dump(machine.generate_config(), f, indent=4)

# %%
